demo_app/urls.py
from django.urls import path
from demo_app import views

urlpatterns=[
    path('contact_us/', views.contact_us, name='contact'),
    path('list_students/', views.list_students, name="list_students"),
    path('add_student/', views.add_student, name="add_student"),
    path('delete_student/<int:id>/', views.delete_student, name="delete_student"),
    path('edit_student/<int:id>/', views.EditStudent.as_view(), name="edit_student"),
    path('login/', views.user_login, name="user_login"),
    path('logout/', views.user_logout, name='user_logout'),
    path('register/', views.user_register, name="user_register"),
    path('list_rooms/', views.ListRooms.as_view(), name='list_rooms'),
    path('detail_room/<int:id>/', views.RoomDetail.as_view(), name='detail_room'),
    path('contact_us/', views.ContactView.as_view(), name='contact'),
    path('add_room/', views.RoomCreateView.as_view(), name='add_room'),
    path('edit_room/<int:id>/', views.RoomUpdateView.as_view(), name='edit_room'),
    path('delete_room/<int:id>/', views.RoomDeleteView.as_view(), name='delete_room')
]

demo_app2/urls.py
from django.urls import path
from demo_app2 import views

urlpatterns=[
    path('index/', views.index)
]

demo_class6/urls.py
from django.contrib import admin
from django.urls import path, include
from demo_app import urls as demo_app_url
from demo_app2 import urls as demo_app2_url
from django.conf.urls.static import static
from demo_class6 import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('d1/', include(demo_app_url)),
    path('d2/', include(demo_app2_url))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

demo_app/models.py
from django.db import models


# Create your models here.
class Room(models.Model):
    room_no = models.IntegerField()
    floor_no = models.IntegerField()

    def __str__(self):
        return "F"+str(self.floor_no)+"R"+str(self.room_no)



class Student(models.Model):
    name = models.CharField(max_length=255)
    roll = models.IntegerField()
    sec = models.CharField(max_length=12)
    room = models.ForeignKey(Room, on_delete=models.PROTECT, null=True)
    photo = models.ImageField(upload_to='student_pics', default='test.png')


class Department(models.Model):
    name = models.CharField(max_length=255, null=False)
    code = models.IntegerField()


class DepartmentHead(models.Model):
    name = models.CharField(max_length=255)
    department = models.OneToOneField(Department, on_delete=models.CASCADE)


class Subject(models.Model):
    name = models.CharField(max_length=240)
    code = models.CharField(max_length=4)
    student = models.ManyToManyField(Student, related_name='student')

demo_app/forms.py
from django import forms
from demo_app.models import Student, Room
from django.contrib.auth.models import User


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = "__all__"


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'password', 'first_name', 'last_name', 'email', )


class RoomForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = '__all__'

demo_app/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404, reverse
from demo_app.models import Student, Room
from demo_app.forms import StudentForm, LoginForm, RegistrationForm, RoomForm
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages
from django.views import View
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView

# Create your views here.
def contact_us(request):
    return HttpResponse("contact page")


@login_required(login_url='/d1/login/')
def list_students(request):
    if request.method == 'GET':
        students = Student.objects.all()
        return render(request, 'list_students.html', {"students":students})


def add_student(request):
    if request.method == 'GET':
        student_form = StudentForm()
        return render(request, "add_student.html", {"form":student_form})
    elif request.method == 'POST':
        student_form = StudentForm(request.POST, request.FILES)
        if student_form.is_valid():
            student_form.save()
            messages.success(request, "Addition successful")
        return redirect('list_students')


def delete_student(request, id):
    try:
        student = Student.objects.get(id=id)
        student.delete()
        messages.success(request, "Deletion Successful")
        return redirect("list_students")
    except:
        messages.error(request, "student with id "+str(id)+" not found")
        return redirect("list_students")


class EditStudent(LoginRequiredMixin, View):
    login_url = 'd1/login/'
    def get(self, request, id):
        student = Student.objects.get(id=id)
        form = StudentForm(instance=student)
        return render(request, 'edit_student.html', {"form":form, "student_id":id})

    def post(self, request, id):
        student = Student.objects.get(id=id)
        student_form = StudentForm(request.POST, request.FILES, instance=student)
        if student_form.is_valid():
            student_form.save()
            return redirect('list_students')
        # else:


def user_login(request):
    if request.method == 'GET':
        login_form = LoginForm()
        return render(request, 'login.html', {"login_form":login_form})

    elif request.method == 'POST':
        username = request.POST['username']
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            login(request, user=user)
            return redirect('list_students')
        else:
            messages.error(request, "Invalid username or password")
            return redirect('user_login')


def user_logout(request):
    logout(request)
    return redirect('user_login')


def user_register(request):
    if request.method == 'GET':
        register_form = RegistrationForm()
        return render(request, 'register.html', {"register_form":register_form})

    elif request.method == 'POST':
        user = RegistrationForm(request.POST)
        if user.is_valid():
            user = user.save()
            user.set_password(user.password)
            user.save()
            return redirect('user_login')


class ListRooms(LoginRequiredMixin, ListView):

    login_url = '/d1/login/'
    template_name = 'list_room.html'
    queryset = Room.objects.all()


class RoomDetail(LoginRequiredMixin, DetailView):

    login_url = '/d1/login/'
    template_name = 'detail_room.html'

    def get_object(self, queryset=None):
        return get_object_or_404(Room, id=self.kwargs['id'])


class ContactView(TemplateView):
     template_name = 'contact_us.html'


class RoomCreateView(LoginRequiredMixin, CreateView):

    login_url = '/d1/login/'
    template_name = 'room_create.html'
    form_class = RoomForm
    success_url = '/d1/list_rooms/'

    # def get_success_url(self):
    #     return reverse('list_rooms')


class RoomUpdateView(LoginRequiredMixin, UpdateView):

    template_name = 'room_update.html'
    form_class = RoomForm
    login_url = '/d1/login/'

    def get_object(self, queryset=None):
        return get_object_or_404(Room, id=self.kwargs['id'])

    def get_success_url(self):
        return reverse('list_rooms')


class RoomDeleteView(LoginRequiredMixin, DeleteView):

    login_url = '/d1/login/'
    template_name = 'delete_room.html'

    def get_object(self, queryset=None):
        return get_object_or_404(Room, id=self.kwargs['id'])

    # def get(self, *args, **kwargs):
    #     return self.post(*args, **kwargs)

    def get_success_url(self):
        return reverse('list_rooms')

    def post(self, request, *args, **kwargs):
        try:
            room = Room.objects.get(id = self.kwargs['id'])
            room.delete()
            return redirect('list_rooms')
        except:
            messages.error(request, "Can't delete this room")
            return redirect('list_rooms')

demo_app2/views.py
from django.shortcuts import render, HttpResponse

# Create your views here.

def index(request):
    list_books = ['physics', 'math', 'biology', 'computer']
    context = {
        'list_books': list_books,
        'list_auths': ['a', 'b', 'c'],
        'is_login': True
    }
    return render(request, "index.html",
                  context=context)

templates/add_student.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Add Student{% endblock %}
{% block content %}
    <div class="col-sm-4">
        <form action="{% url 'add_student' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form | crispy }}
            <input type="submit" value="submit" class="btn btn-success">
        </form>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome/css/all.css' %}">
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
{% if user.is_authenticated %}
    <ul class="nav justify-content-end">
        <li class="nav-item">
        <a class="nav-link active" href="{% url 'list_students' %}">Student</a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'user_logout' %}" tabindex="-1">Logout</a>
        </li>
    </ul>
{% endif %}
    {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                <div class="alert alert-success">
                    {{ message }}
                </div>
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <div class="alert alert-danger">
                    <i class="fa fa-exclamation-triangle"></i> {{ message }}
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
        {% block content %}
        {% endblock %}
</body>
</html>

templates/contact_us.html
Contact us at contact@training.com

templates/delete_room.html
{% extends 'base.html' %}

{% block title %}Delete{% endblock %}

{% block content %}
    <form method="post">
    {% csrf_token %}
        <h1>Are you sure, you want to delete {{ object }}??</h1>
        <input type="submit" class="btn btn-danger" value="Delete">
    </form>
{% endblock %}

templates/detail_room.html
{% extends 'base.html' %}

{% block content%}
    {{ object.room_no }}
    {{ object.floor_no }}
{% endblock %}

templates/edit_student.html
{% extends 'base.html' %}
{% block title %}Edit Student{% endblock %}
{% block content %}
    <form action="{% url 'edit_student' id=student_id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="submit" class="btn btn-success">
    </form>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title %}
    index
{% endblock %}
{% block content %}
    <h1>Test Title</h1>
    <p id="div_brown">test text
    <a href="{% url 'contact' %}">click</a>
    </p>
    <h1 class="red-color">This is a contact page</h1>
    {% if is_login %}
        user is logged in
    {% else %}
        user is not logged in
    {% endif %}
    {{ is_login }}
    <table border="1">
    {% for book in list_books %}
        <tr>
            <td>
                {{ book }}
            </td>
        </tr>
    {% endfor %}
    </table>
{% endblock %}

templates/list_room.html
{% extends 'base.html' %}

{% block title %}List Rooms{% endblock %}
{% block content %}
    <table class="table">
    <thead>
        <tr>
            <th>Room Number</th>
            <th>Floor Number</th>
            <th>Count</th>
        </tr>
    </thead>
    <tbody>
        {% for instance in object_list %}
            <tr>
            <td>{{ instance.room_no }}</td>
            <td>{{ instance.floor_no }}</td>
            <td>{{ instance.student_set.count }}</td>
            </tr>
        {% endfor %}
    </tbody>
    </table>
{% endblock %}

templates/list_students.html
{% extends 'base.html' %}

{% block title %}List students{% endblock %}
{% block content %}
    <a class="btn btn-primary" href="{% url 'add_student' %}">Add new</a>
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Roll</th>
            <th>Section</th>
            <th>Room</th>
            <th>Photo</th>
            <th>Delete</th>
            <th>Edit</th>
        </tr>
    </thead>
    <tbody>
        {% for student in students %}
            <tr>
                <td>{{ student.name }}</td>
                <td>{{ student.roll }}</td>
                <td>{{ student.sec }}</td>
                <td>{{ student.room.room_no }}</td>
                <td><img src="{{ student.photo.url }}" height="100px"></td>
                <td><a class="btn btn-danger" href="{% url 'delete_student' id=student.id %}">Delete</a></td>
                <td><a class="btn btn-warning" href="{% url 'edit_student' id=student.id %}">Edit</a></td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="jumbotron">
    <h1>LOGIN FORM</h1>
    </div>
    <div class="offset-4 col-sm-4">
        <form action="{% url 'user_login' %}" method="post">
        {% csrf_token %}
        {{ login_form | crispy }}
        <input type="submit" value="LOGIN" class="btn btn-dark">
    </form>
    </div>
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{%  load crispy_forms_tags %}
{% block title %} Register {% endblock %}
{% block content %}
    <div class="col-sm-4">
        <form action="{% url 'user_register' %}" method="post">
            {% csrf_token %}
            {{ register_form | crispy }}
            <input type="submit" value="Register" class="btn btn-success">
        </form>
    </div>
{% endblock %}

templates/room_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Add Room{% endblock %}
{% block content %}
    <div class="col-sm-4">
        <form action="{% url 'add_room' %}" method="post">
            {% csrf_token %}
            {{ form | crispy }}
            <input type="submit" value="submit" class="btn btn-success">
        </form>
    </div>
{% endblock %}

templates/room_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Add Room{% endblock %}
{% block content %}
    <div class="col-sm-4">
        <form action="{% url 'edit_room' id=object.id %}" method="post">
            {% csrf_token %}
            {{ form | crispy }}
            <input type="submit" value="submit" class="btn btn-success">
        </form>
    </div>
{% endblock %}